In [1]:
import cv2
import json
import numpy as np
import random
from copy import deepcopy

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from tqdm import tqdm

# set seed

In [2]:
torch.manual_seed(0)
random.seed(0)
np.random.seed(0)

g = torch.Generator()
g.manual_seed(0)

# dataset

In [3]:
class CustomDataset(Dataset):
    def __init__(self, json_path_list):
        self.annotations = []
        for json_path in json_path_list:
            with open(json_path, 'r') as f:
                annotations = json.load(f)
            self.annotations.extend(annotations['annotations'])
    
    def __len__(self):
        return len(self.annotations)
    
    def __getitem__(self, idx):
        anno = self.annotations[idx]
        label = anno['label']
        label = np.eye(5)[label].astype(np.float32)
        
        # label smoothing
        label = label * .9 + 0.1 / 5 
        
        kpts_ = np.array(anno['kpts']).reshape(-1, 2)
        kpts_ = preprocessing(kpts_)
        
        return label, kpts_.astype(np.float32)
    
    
def preprocessing(kpts):
    kpts_ = deepcopy(kpts)
    kpts_ = (kpts_ - kpts_.min(axis=0)) / (kpts_.max(axis=0) - kpts_.min(axis=0))
    return kpts_.flatten()

In [4]:
ds = CustomDataset([f'./data/annotation_{i}.json' for i in range(5)])
len(ds)

2505

In [5]:
ds[0]

(array([0.91999996, 0.02      , 0.02      , 0.02      , 0.02      ],
       dtype=float32),
 array([0.21594635, 1.        , 0.443099  , 0.9287557 , 0.6469579 ,
        0.7714337 , 0.8361737 , 0.6478518 , 1.        , 0.57608795,
        0.49768278, 0.4669195 , 0.509404  , 0.2612543 , 0.503457  ,
        0.12828362, 0.49311274, 0.        , 0.34171033, 0.47398508,
        0.27542248, 0.46475977, 0.304567  , 0.6385949 , 0.35247087,
        0.6362982 , 0.19208448, 0.5076398 , 0.12309471, 0.5348637 ,
        0.18273547, 0.69105816, 0.24475259, 0.6733748 , 0.05024889,
        0.5485357 , 0.        , 0.564812  , 0.06049323, 0.6850807 ,
        0.11008564, 0.7059657 ], dtype=float32))

In [6]:
total = len(ds)
num_train = int(total * .8)
ds_train, ds_valid = torch.utils.data.random_split(ds, [num_train, total - num_train], generator=g)
print(f'train: {len(ds_train)} / valid: {len(ds_valid)}')

train: 2004 / valid: 501


In [7]:
labels, cnt = np.unique([ds_valid.dataset.annotations[i]['label'] for i in ds_valid.indices], return_counts=True)
print({l:c for l, c in zip(labels, cnt)})

{0: 106, 1: 105, 2: 116, 3: 84, 4: 90}


# model

In [8]:
m = nn.BatchNorm1d(100)
# Without Learnable Parameters
m = nn.BatchNorm1d(100, affine=False)
input = torch.randn(20, 100)
output = m(input)

In [9]:
output.shape

torch.Size([20, 100])

In [10]:
simple_model = nn.Sequential(
    nn.Linear(42, 20),
    nn.BatchNorm1d(20),
    nn.ReLU(True,),
    nn.Linear(20, 10),
    nn.BatchNorm1d(10),
    nn.ReLU(True,),
    nn.Linear(10, 5),
    nn.Sigmoid(),
)

In [11]:
test = simple_model(torch.randn(2, 42))
print('shape:', test.size())

shape: torch.Size([2, 5])


# training

In [12]:
EPOCHS = 60
BS = 64

In [13]:
train_loader = DataLoader(ds_train, BS, shuffle=True, drop_last=True, num_workers=8)
valid_loader = DataLoader(ds_valid, BS, shuffle=False, drop_last=False, num_workers=8)

In [14]:
# criterion = nn.CrossEntropyLoss()
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(simple_model.parameters(), lr=2e-3)
scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=2e-3, epochs=EPOCHS, steps_per_epoch=len(train_loader))

baseline: 0.872255489021956

label smoothing: 0.8343313373253493

In [15]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
simple_model = simple_model.to(device)

all_valid_pred = []
all_valid_label = []

for epoch in range(EPOCHS):
    simple_model.train()
    epoch_loss = 0.
    for label, input_ in tqdm(train_loader):
        label, input_ = label.to(device), input_.to(device)
        
        pred = simple_model(input_)
        loss = criterion(pred, label)
        
        epoch_loss += loss.detach().item() * label.size()[0]
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        scheduler.step()
    print(f'[epoch {epoch}] loss: {epoch_loss / len(ds_train)}, lr: {scheduler.get_lr()}')
    
    simple_model.eval()
    
    correct = 0
    for label, input_ in tqdm(valid_loader):
        label, input_ = label.to(device), input_.to(device)
        
        with torch.no_grad():
            pred = simple_model(input_)
            cls_pred = pred.argmax(dim=-1)
            cls_true = label.argmax(dim=-1)
            
            correct += (cls_pred == cls_true).sum().item()
            
            if epoch == EPOCHS - 1:
                all_valid_pred.extend(cls_pred.detach().cpu().numpy().tolist())
                all_valid_label.extend(cls_true.detach().cpu().numpy().tolist())
            
    print(f'--val acc: {correct / len(ds_valid)}')

100%|██████████| 31/31 [00:00<00:00, 51.24it/s]
/usr/lib/python3/dist-packages/torch/optim/lr_scheduler.py:1289: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "


[epoch 0] loss: 0.7072491845684851, lr: [9.463683876508033e-05]


100%|██████████| 8/8 [00:00<00:00, 38.47it/s]


--val acc: 0.22355289421157684


100%|██████████| 31/31 [00:00<00:00, 104.03it/s]


[epoch 1] loss: 0.6898460369148178, lr: [0.00013810102787483098]


100%|██████████| 8/8 [00:00<00:00, 41.87it/s]


--val acc: 0.35728542914171657


100%|██████████| 31/31 [00:00<00:00, 114.98it/s]


[epoch 2] loss: 0.6693898141978981, lr: [0.00020906719581247307]


100%|██████████| 8/8 [00:00<00:00, 42.93it/s]


--val acc: 0.44510978043912175


100%|██████████| 31/31 [00:00<00:00, 111.94it/s]


[epoch 3] loss: 0.6414447868179657, lr: [0.0003053713418324246]


100%|██████████| 8/8 [00:00<00:00, 41.88it/s]


--val acc: 0.5688622754491018


100%|██████████| 31/31 [00:00<00:00, 116.39it/s]


[epoch 4] loss: 0.6100162574631012, lr: [0.00042407682373113865]


100%|██████████| 8/8 [00:00<00:00, 42.28it/s]


--val acc: 0.6986027944111777


100%|██████████| 31/31 [00:00<00:00, 113.84it/s]


[epoch 5] loss: 0.5771463493149199, lr: [0.0005615639060938596]


100%|██████████| 8/8 [00:00<00:00, 42.39it/s]


--val acc: 0.7065868263473054


100%|██████████| 31/31 [00:00<00:00, 107.72it/s]


[epoch 6] loss: 0.5420241441555366, lr: [0.000713640138385537]


100%|██████████| 8/8 [00:00<00:00, 40.79it/s]


--val acc: 0.7285429141716567


100%|██████████| 31/31 [00:00<00:00, 113.18it/s]


[epoch 7] loss: 0.5034630027359831, lr: [0.0008756681970810574]


100%|██████████| 8/8 [00:00<00:00, 41.61it/s]


--val acc: 0.7365269461077845


100%|██████████| 31/31 [00:00<00:00, 105.92it/s]


[epoch 8] loss: 0.4621715345782434, lr: [0.0010427072934917855]


100%|██████████| 8/8 [00:00<00:00, 39.73it/s]


--val acc: 0.7544910179640718


100%|██████████| 31/31 [00:00<00:00, 109.62it/s]


[epoch 9] loss: 0.41588957438211954, lr: [0.001209663835280994]


100%|██████████| 8/8 [00:00<00:00, 40.49it/s]


--val acc: 0.7684630738522954


100%|██████████| 31/31 [00:00<00:00, 103.30it/s]


[epoch 10] loss: 0.37036804762667047, lr: [0.0013714467474842179]


100%|██████████| 8/8 [00:00<00:00, 40.35it/s]


--val acc: 0.7405189620758483


100%|██████████| 31/31 [00:00<00:00, 107.13it/s]


[epoch 11] loss: 0.3279256478041232, lr: [0.001523122716766323]


100%|██████████| 8/8 [00:00<00:00, 39.33it/s]


--val acc: 0.8243512974051896


100%|██████████| 31/31 [00:00<00:00, 104.73it/s]


[epoch 12] loss: 0.2913271414781521, lr: [0.0016600666249878945]


100%|██████████| 8/8 [00:00<00:00, 39.12it/s]


--val acc: 0.9680638722554891


100%|██████████| 31/31 [00:00<00:00, 110.64it/s]


[epoch 13] loss: 0.2593060220311026, lr: [0.0017781025848478931]


100%|██████████| 8/8 [00:00<00:00, 39.83it/s]


--val acc: 0.9620758483033932


100%|██████████| 31/31 [00:00<00:00, 105.35it/s]


[epoch 14] loss: 0.22906568473922517, lr: [0.001873631276944334]


100%|██████████| 8/8 [00:00<00:00, 40.94it/s]


--val acc: 0.9860279441117764


100%|██████████| 31/31 [00:00<00:00, 107.43it/s]


[epoch 15] loss: 0.20638242500746798, lr: [0.0019437397053112704]


100%|██████████| 8/8 [00:00<00:00, 38.75it/s]


--val acc: 0.9141716566866267


100%|██████████| 31/31 [00:00<00:00, 106.46it/s]


[epoch 16] loss: 0.1855736149999196, lr: [0.0019862900246110362]


100%|██████████| 8/8 [00:00<00:00, 41.60it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 108.39it/s]


[epoch 17] loss: 0.17241026826961312, lr: [0.0019999970889756826]


100%|██████████| 8/8 [00:00<00:00, 41.19it/s]


--val acc: 0.998003992015968


100%|██████████| 31/31 [00:00<00:00, 111.73it/s]


[epoch 18] loss: 0.16286245601143903, lr: [0.0019970205903154987]


100%|██████████| 8/8 [00:00<00:00, 43.19it/s]


--val acc: 0.9900199600798403


100%|██████████| 31/31 [00:00<00:00, 107.98it/s]


[epoch 19] loss: 0.15957676150841626, lr: [0.001988468370454814]


100%|██████████| 8/8 [00:00<00:00, 40.02it/s]


--val acc: 0.9960079840319361


100%|██████████| 31/31 [00:00<00:00, 116.17it/s]


[epoch 20] loss: 0.15335092192400476, lr: [0.0019743882568761923]


100%|██████████| 8/8 [00:00<00:00, 39.28it/s]


--val acc: 0.998003992015968


100%|██████████| 31/31 [00:00<00:00, 108.03it/s]


[epoch 21] loss: 0.15103383835204348, lr: [0.0019548589912861884]


100%|██████████| 8/8 [00:00<00:00, 42.30it/s]


--val acc: 0.998003992015968


100%|██████████| 31/31 [00:00<00:00, 113.61it/s]


[epoch 22] loss: 0.14628475440476468, lr: [0.0019299897892597869]


100%|██████████| 8/8 [00:00<00:00, 43.37it/s]


--val acc: 0.998003992015968


100%|██████████| 31/31 [00:00<00:00, 111.90it/s]


[epoch 23] loss: 0.14645608980022742, lr: [0.0018999197294626046]


100%|██████████| 8/8 [00:00<00:00, 44.76it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 112.69it/s]


[epoch 24] loss: 0.14632205668085826, lr: [0.0018648169758665749]


100%|██████████| 8/8 [00:00<00:00, 37.24it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 110.55it/s]


[epoch 25] loss: 0.14377617931175612, lr: [0.001824877837308805]


100%|██████████| 8/8 [00:00<00:00, 40.90it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.81it/s]


[epoch 26] loss: 0.14306792908323976, lr: [0.0017803256696529279]


100%|██████████| 8/8 [00:00<00:00, 42.31it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.20it/s]


[epoch 27] loss: 0.1417798491533169, lr: [0.0017314096266925114]


100%|██████████| 8/8 [00:00<00:00, 43.02it/s]


--val acc: 0.9940119760479041


100%|██████████| 31/31 [00:00<00:00, 110.09it/s]


[epoch 28] loss: 0.1428269407230461, lr: [0.0016784032667819782]


100%|██████████| 8/8 [00:00<00:00, 40.20it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.59it/s]


[epoch 29] loss: 0.14169240426160618, lr: [0.0016216030229873227]


100%|██████████| 8/8 [00:00<00:00, 39.42it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.19it/s]


[epoch 30] loss: 0.13959386724673822, lr: [0.0015613265453121616]


100%|██████████| 8/8 [00:00<00:00, 42.64it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 115.64it/s]


[epoch 31] loss: 0.13862923757282797, lr: [0.0014979109242700627]


100%|██████████| 8/8 [00:00<00:00, 43.74it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 108.27it/s]


[epoch 32] loss: 0.14064676461819403, lr: [0.0014317108057376557]


100%|██████████| 8/8 [00:00<00:00, 40.75it/s]


--val acc: 0.9940119760479041


100%|██████████| 31/31 [00:00<00:00, 112.76it/s]


[epoch 33] loss: 0.1411473722514992, lr: [0.0013630964076310345]


100%|██████████| 8/8 [00:00<00:00, 42.06it/s]


--val acc: 0.9940119760479041


100%|██████████| 31/31 [00:00<00:00, 108.35it/s]


[epoch 34] loss: 0.14021606121710437, lr: [0.001292451449496993]


100%|██████████| 8/8 [00:00<00:00, 41.24it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 110.25it/s]


[epoch 35] loss: 0.1395657386132581, lr: [0.0012201710065976711]


100%|██████████| 8/8 [00:00<00:00, 40.63it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 110.88it/s]


[epoch 36] loss: 0.13964868971925534, lr: [0.0011466593004894302]


100%|██████████| 8/8 [00:00<00:00, 40.09it/s]


--val acc: 0.998003992015968


100%|██████████| 31/31 [00:00<00:00, 116.84it/s]


[epoch 37] loss: 0.1387751621162582, lr: [0.0010723274384519426]


100%|██████████| 8/8 [00:00<00:00, 44.41it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 107.61it/s]


[epoch 38] loss: 0.14007301578026807, lr: [0.0009975911144095228]


100%|██████████| 8/8 [00:00<00:00, 40.06it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.02it/s]


[epoch 39] loss: 0.13976397247847444, lr: [0.0009228682842020823]


100%|██████████| 8/8 [00:00<00:00, 40.89it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 110.54it/s]


[epoch 40] loss: 0.13831993300995665, lr: [0.0008485768282065336]


100%|██████████| 8/8 [00:00<00:00, 41.31it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.50it/s]


[epoch 41] loss: 0.13831844015749628, lr: [0.000775132214380214]


100%|██████████| 8/8 [00:00<00:00, 40.65it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 105.77it/s]


[epoch 42] loss: 0.1381675321422889, lr: [0.0007029451747955407]


100%|██████████| 8/8 [00:00<00:00, 43.86it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.83it/s]


[epoch 43] loss: 0.1393028300203487, lr: [0.0006324194086596515]


100%|██████████| 8/8 [00:00<00:00, 42.70it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 113.14it/s]


[epoch 44] loss: 0.1387116813850022, lr: [0.0005639493246646838]


100%|██████████| 8/8 [00:00<00:00, 43.39it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 106.55it/s]


[epoch 45] loss: 0.13833295846889596, lr: [0.0004979178352943804]


100%|██████████| 8/8 [00:00<00:00, 43.01it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 113.47it/s]


[epoch 46] loss: 0.1384389647942579, lr: [0.0004346942154221573]


100%|██████████| 8/8 [00:00<00:00, 42.08it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.51it/s]


[epoch 47] loss: 0.13823278126364458, lr: [0.0003746320371762205]


100%|██████████| 8/8 [00:00<00:00, 41.33it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 114.56it/s]


[epoch 48] loss: 0.13826043877059113, lr: [0.00031806719262080115]


100%|██████████| 8/8 [00:00<00:00, 42.62it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 109.75it/s]


[epoch 49] loss: 0.1382678935151852, lr: [0.0002653160153114834]


100%|██████████| 8/8 [00:00<00:00, 43.32it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.29it/s]


[epoch 50] loss: 0.13808771378979712, lr: [0.00021667351122964338]


100%|██████████| 8/8 [00:00<00:00, 43.18it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 108.41it/s]


[epoch 51] loss: 0.13714694929218102, lr: [0.00017241170898933824]


100%|██████████| 8/8 [00:00<00:00, 43.43it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.58it/s]


[epoch 52] loss: 0.13753400591319193, lr: [0.00013277813854294793]


100%|██████████| 8/8 [00:00<00:00, 42.27it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 107.64it/s]


[epoch 53] loss: 0.1387868936428291, lr: [9.799444689327728e-05]


100%|██████████| 8/8 [00:00<00:00, 41.63it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 118.16it/s]


[epoch 54] loss: 0.13792158362870208, lr: [6.82551585536054e-05]


100%|██████████| 8/8 [00:00<00:00, 41.67it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 111.61it/s]


[epoch 55] loss: 0.13816576470396, lr: [4.372658768770261e-05]


100%|██████████| 8/8 [00:00<00:00, 41.45it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 116.93it/s]


[epoch 56] loss: 0.13738283616102145, lr: [2.454590801356266e-05]


100%|██████████| 8/8 [00:00<00:00, 42.22it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 115.75it/s]


[epoch 57] loss: 0.13794230463024146, lr: [1.0820385672328905e-05]


100%|██████████| 8/8 [00:00<00:00, 41.50it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 106.80it/s]


[epoch 58] loss: 0.1369251234088829, lr: [2.6267793525220675e-06]


100%|██████████| 8/8 [00:00<00:00, 40.39it/s]


--val acc: 1.0


100%|██████████| 31/31 [00:00<00:00, 112.17it/s]


[epoch 59] loss: 0.1375357752550624, lr: [1.0911024317473058e-08]


100%|██████████| 8/8 [00:00<00:00, 41.32it/s]

--val acc: 1.0


In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
confusion_matrix(all_valid_label, all_valid_pred)

array([[106,   0,   0,   0,   0],
       [  0, 105,   0,   0,   0],
       [  0,   0, 116,   0,   0],
       [  0,   0,   0,  84,   0],
       [  0,   0,   0,   0,  90]])

### base

acc: 0.872255489021956


```python
array([[ 98,   8,   0,   0,   0],
       [ 14,  57,  34,   0,   0],
       [  0,   8, 108,   0,   0],
       [  0,   0,   0,  84,   0],
       [  0,   0,   0,   0,  90]])
```

### label smoothing / 0.1

acc: 0.8343313373253493

```python
array([[ 97,   8,   1,   0,   0],
       [ 19,  39,  47,   0,   0],
       [  2,   6, 108,   0,   0],
       [  0,   0,   0,  84,   0],
       [  0,   0,   0,   0,  90]])
```

### batchnorm

acc: 1.0

```python
array([[106,   0,   0,   0,   0],
       [  0, 105,   0,   0,   0],
       [  0,   0, 116,   0,   0],
       [  0,   0,   0,  84,   0],
       [  0,   0,   0,   0,  90]])
```

In [18]:
torch.onnx.export(simple_model, input_[:1], "simple_model.onnx", verbose=True, input_names=['input'], output_names=['output'])

graph(%input : Float(1, 42, strides=[42, 1], requires_grad=0, device=cuda:0),
      %0.weight : Float(20, 42, strides=[42, 1], requires_grad=1, device=cuda:0),
      %0.bias : Float(20, strides=[1], requires_grad=1, device=cuda:0),
      %1.weight : Float(20, strides=[1], requires_grad=1, device=cuda:0),
      %1.bias : Float(20, strides=[1], requires_grad=1, device=cuda:0),
      %1.running_mean : Float(20, strides=[1], requires_grad=0, device=cuda:0),
      %1.running_var : Float(20, strides=[1], requires_grad=0, device=cuda:0),
      %3.weight : Float(10, 20, strides=[20, 1], requires_grad=1, device=cuda:0),
      %3.bias : Float(10, strides=[1], requires_grad=1, device=cuda:0),
      %4.weight : Float(10, strides=[1], requires_grad=1, device=cuda:0),
      %4.bias : Float(10, strides=[1], requires_grad=1, device=cuda:0),
      %4.running_mean : Float(10, strides=[1], requires_grad=0, device=cuda:0),
      %4.running_var : Float(10, strides=[1], requires_grad=0, device=cuda:0),
    

In [19]:
import onnxruntime as ort
from tqdm import tqdm
import numpy as np

ort_session = ort.InferenceSession("simple_model.onnx")

for _ in tqdm(range(100)):
    outputs = ort_session.run(
        ['output'],
        {"input": np.random.randn(1, 42).astype(np.float32)},
    )
    

100%|██████████| 100/100 [00:00<00:00, 35481.80it/s]
